# Highlight.io services for the hobby deployment.
services:
    backend:
        container_name: backend
        image: ${BACKEND_IMAGE_NAME-ghcr.io/highlight/highlight-backend:latest}
        restart: on-failure
        ports:
            - '0.0.0.0:8081:8082'
        volumes:
            - highlight-data:/highlight-data
        env_file: .env

    frontend:
        container_name: frontend
        image: ${FRONTEND_IMAGE_NAME-ghcr.io/highlight/highlight-frontend:latest}
        restart: on-failure
        ports:
            - '0.0.0.0:3001:3000'
            - '0.0.0.0:6006:6006'
        env_file: .env

volumes:
    highlight-data:
